/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmigosDonBosco;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

import AmigosDonBosco.materialCD;
import AmigosDonBosco.materialDVD;
import AmigosDonBosco.materialLibro;
import AmigosDonBosco.materialRevista;


/**
 *
 * @author Cartagena
 */
public class mediateca_agregar extends javax.swing.JFrame {
    
    private final materialCD MATERIAL_CD            = new materialCD();
    private final materialDVD MATERIAL_DVD          = new materialDVD();
    private final materialLibro MATERIAL_LIBRO      = new materialLibro();
    private final materialRevista MATERIAL_REVISTA  = new materialRevista();
    
    /**
     * Creates new form mediateca_agregar
     */
    public mediateca_agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        agregarCd = new javax.swing.JButton();
        agregarDvd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        agregarLibro = new javax.swing.JButton();
        agregarRevista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Material");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        agregarCd.setText("Agregar CD");
        agregarCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCdActionPerformed(evt);
            }
        });

        agregarDvd.setText("Agregar DVD");
        agregarDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDvdActionPerformed(evt);
            }
        });

        jLabel1.setText("Material Audiovisual");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(agregarDvd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarCd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(agregarCd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarDvd)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        agregarLibro.setText("Agregar Libro");
        agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLibroActionPerformed(evt);
            }
        });

        agregarRevista.setText("Agregar Revista");
        agregarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRevistaActionPerformed(evt);
            }
        });

        jLabel3.setText("Material Escrito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(agregarRevista, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel3))))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(agregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarRevista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        adminMediateca.main();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        adminMediateca.main();
    }//GEN-LAST:event_formWindowClosed

    private void agregarCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCdActionPerformed
        boolean validate = true;
        String tmp;
        int result;

        String id = "CDA"+String.format("%05d", (MATERIAL_CD.countRows() + 1));
        String titulo = "";
        String artista = "";
        String genero = "";
        int duracion = 0;
        int numeroCanciones = 0;
        int unidades = 0;
        
        titulo = JOptionPane.showInputDialog("Ingrese el titulo del CD:");
        artista = JOptionPane.showInputDialog("Ingrese el nombre del artista:");
        genero = JOptionPane.showInputDialog("Ingrese el genero del CD:");
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese la duracion en minutos de la cancion");
            try{
                duracion = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese el numero de canciones:");
            try{
                numeroCanciones = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese el numero de unidades:");
            try{
                unidades = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        // Enviamos los datos a la BD
        result = MATERIAL_CD.insert(id, titulo, artista, genero, duracion, numeroCanciones, unidades);
        
        if(result == 1){
            JOptionPane.showMessageDialog(null, "Se guardo el nuevo CD", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "No Se guardo el nuevo CD", "", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_agregarCdActionPerformed

    private void agregarDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDvdActionPerformed
        boolean validate = true;
        String tmp;
        int result;
        
        String codd = "DVD"+String.format("%05d", (MATERIAL_DVD.countRows() + 1));
        String titulo = "";
        String director = "";
        int duracion = 0; 
        String genero = ""; 
        int unidades = 0;
        
        titulo = JOptionPane.showInputDialog("Ingrese el titulo del DVD:");
        director = JOptionPane.showInputDialog("Ingrese el nombre del director:");
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("La duracion del DVD:");
            try{
                duracion = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        genero = JOptionPane.showInputDialog("Ingrese el genero del DVD:");
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese las unidades del DVD:");
            try{
                unidades = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        // Enviamos los datos a la BD
        result = MATERIAL_DVD.insert(codd, titulo, director, duracion, genero, unidades);
        
        if(result == 1){
            JOptionPane.showMessageDialog(null, "Se guardo el nuevo DVD", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "No Se guardo el nuevo DVD", "", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_agregarDvdActionPerformed

    private void agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLibroActionPerformed
        boolean validate = true;
        String tmp;
        int result;
        
        String codl = "LIB"+String.format("%05d", (MATERIAL_LIBRO.countRows() + 1));
        String titulo = ""; 
        String autor = "";
        int numeroPaginas = 0;
        String editorial = ""; 
        String isbn = "";
        String anioPublicacion = ""; 
        int unidades = 0;
        
        titulo = JOptionPane.showInputDialog("Ingrese el titulo del LIBRO:");
        autor = JOptionPane.showInputDialog("Ingrese el AUTOR del LIBRO:");
        
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese el numero de paginas del LIBRO:");
            try{
                numeroPaginas = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        editorial = JOptionPane.showInputDialog("Ingrese la editorial del LIBRO:");
        isbn = JOptionPane.showInputDialog("Ingrese el isbn del LIBRO:");
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese el anio de publicacion del LIBRO:");
            try{
                Integer.parseInt(tmp);
                anioPublicacion = tmp;
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese las unidades del LIBRO:");
            try{
                unidades = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }
        
        // Enviamos los datos a la BD
        result = MATERIAL_LIBRO.insert(codl,titulo, autor, numeroPaginas, editorial, isbn, anioPublicacion, unidades);
        
        if(result == 1){
            JOptionPane.showMessageDialog(null, "Se guardo el nuevo LIBRO", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "No Se guardo el nuevo LIBRO", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_agregarLibroActionPerformed

    private void agregarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRevistaActionPerformed
        boolean validate = true;
        String tmp;
        int result;
        
        String codr = "REV"+String.format("%05d", (MATERIAL_REVISTA.countRows() + 1));;;
        String titulo = ""; 
        String editorial= ""; 
        String periocidad= ""; 
        Date fechaPublicacion = null;
        int unidades = 0;
        
        titulo = JOptionPane.showInputDialog("Ingrese el titulo de la REVISTA:");
        editorial = JOptionPane.showInputDialog("Ingrese la editorial de la REVISTA:");
        
        validate = true;
        while(validate){
            periocidad = JOptionPane.showInputDialog("Ingrese la periocidad de la REVISTA digite 'semanal','quincenal','mensual','trimestral','semestral','anual':");
            switch(periocidad){
                case "semanal":
                    validate = false;
                    break;
                case "quincenal":
                    validate = false;
                    break;
                case "mensual":
                    validate = false;
                    break;
                case "trimestral":
                    validate = false;
                    break;
                case "semestral":
                    validate = false;
                    break;
                case "anual":
                    validate = false;
                    break;
            }
            if(validate){
                JOptionPane.showMessageDialog(null, "Digite una opcion valida", "", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        validate = true;
        String fecha = "";
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        while(validate){
            fecha = JOptionPane.showInputDialog("Ingrese la fecha en formato YYYY-MM-DD:");
            if (fecha != null && fecha.matches("\\d{4}-\\d{2}-\\d{2}")) {
                try {
                    java.util.Date utilDate = formatter.parse(fecha);
                    fechaPublicacion = new java.sql.Date(utilDate.getTime());
                } catch (ParseException ex) {
                    Logger.getLogger(mediateca_agregar.class.getName()).log(Level.SEVERE, null, ex);
                    ex.printStackTrace();
                }
                validate = false;
            } else {
                JOptionPane.showMessageDialog(null, "Formato incorrecto. Use YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        validate = true;
        while(validate){
            tmp = JOptionPane.showInputDialog("Ingrese las unidades de la revista:");
            try{
                unidades = Integer.parseInt(tmp);
                validate = false;
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor entero valido");
                validate = true;
            }
        }

        result = MATERIAL_REVISTA.insert( codr,  titulo,  editorial,  periocidad,  fechaPublicacion, unidades);
        
        if(result == 1){
            JOptionPane.showMessageDialog(null, "Se guardo LA NUEVA REVISTA", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "No Se guardo el nuevo REVISTA", "", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_agregarRevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mediateca_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mediateca_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mediateca_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mediateca_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mediateca_agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCd;
    private javax.swing.JButton agregarDvd;
    private javax.swing.JButton agregarLibro;
    private javax.swing.JButton agregarRevista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
